--# selene: allow(incorrect_standard_library_use)

DOTA_TEAM_GOODGUYS = 2
DOTA_TEAM_BADGUYS = 3
DOTA_TEAM_NEUTRALS = 4
DOTA_TEAM_NOTEAM = 5
DOTA_TEAM_CUSTOM_1 = 6
DOTA_TEAM_CUSTOM_2 = 7
DOTA_TEAM_CUSTOM_3 = 8
DOTA_TEAM_CUSTOM_4 = 9
DOTA_TEAM_CUSTOM_5 = 10
DOTA_TEAM_CUSTOM_6 = 11
DOTA_TEAM_CUSTOM_7 = 12
DOTA_TEAM_CUSTOM_8 = 13
DOTA_TEAM_FIRST = 2
DOTA_TEAM_COUNT = 14
DOTA_TEAM_CUSTOM_COUNT = 8
DOTA_TEAM_CUSTOM_MIN = 6
DOTA_TEAM_CUSTOM_MAX = 13

DOTA_RUNE_INVALID = -1
DOTA_RUNE_DOUBLEDAMAGE = 0
DOTA_RUNE_HASTE = 1
DOTA_RUNE_ILLUSION = 2
DOTA_RUNE_INVISIBILITY = 3
DOTA_RUNE_REGENERATION = 4
DOTA_RUNE_BOUNTY = 5
DOTA_RUNE_ARCANE = 6
DOTA_RUNE_COUNT = 7

DOTA_ITEM_SLOT_1 = 0
DOTA_ITEM_SLOT_2 = 1
DOTA_ITEM_SLOT_3 = 2
DOTA_ITEM_SLOT_4 = 3
DOTA_ITEM_SLOT_5 = 4
DOTA_ITEM_SLOT_6 = 5
DOTA_ITEM_SLOT_7 = 6
DOTA_ITEM_SLOT_8 = 7
DOTA_ITEM_SLOT_9 = 8
DOTA_STASH_SLOT_1 = 9
DOTA_STASH_SLOT_2 = 10
DOTA_STASH_SLOT_3 = 11
DOTA_STASH_SLOT_4 = 12
DOTA_STASH_SLOT_5 = 13
DOTA_STASH_SLOT_6 = 14
DOTA_ITEM_NEUTRAL_ACTIVE_SLOT = 16
DOTA_ITEM_NEUTRAL_PASSIVE_SLOT = 17

ABILITY_TYPE_ATTRIBUTES = 1
ABILITY_TYPE_BASIC = 2
ABILITY_TYPE_HIDDEN = 3
ABILITY_TYPE_ULTIMATE = 4

ABILITY_CAN_BE_UPGRADED = 0
ABILITY_CANNOT_BE_UPGRADED_NOT_UPGRADABLE = 1
ABILITY_CANNOT_BE_UPGRADED_AT_MAX = 2
ABILITY_CANNOT_BE_UPGRADED_REQUIRES_LEVEL = 3
ABILITY_NOT_LEARNABLE = 4

DOTA_DAMAGE_CATEGORY_SPELL = 0
DOTA_DAMAGE_CATEGORY_ATTACK = 1
