root: true
parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "biome"
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-namespace": "off"
  "@typescript-eslint/triple-slash-reference": "off"
