local tablex = require("pl.tablex")

local M = {
  INVENTORY_SLOTS = {
    DOTA_ITEM_SLOT_1,
    DOTA_ITEM_SLOT_2,
    DOTA_ITEM_SLOT_3,
    DOTA_ITEM_SLOT_4,
    DOTA_ITEM_SLOT_5,
    DOTA_ITEM_SLOT_6,
  },
  STASH_SLOTS = {
    DOTA_STASH_SLOT_1,
    DOTA_STASH_SLOT_2,
    DOTA_STASH_SLOT_3,
    DOTA_STASH_SLOT_4,
    DOTA_STASH_SLOT_5,
    DOTA_STASH_SLOT_6,
  },
}

M.SLOTS = {}

tablex.insertvalues(M.SLOTS, M.INVENTORY_SLOTS)
tablex.insertvalues(M.SLOTS, M.STASH_SLOTS)

M.MAX_INVENTORY_SLOTS = #M.INVENTORY_SLOTS
M.MAX_STASH_SLOTS = #M.STASH_SLOTS
M.MAX_SLOTS = #M.SLOTS

return M
