---
root: true
env:
  es6: false
  browser: false
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 3
rules: {}
globals:
  $: readonly
  GameEvents: readonly
  CustomNetTables: readonly
  SteamUGC: readonly
  SteamFriends: readonly
  SteamUtils: readonly
  VRUtils: readonly
  Buffs: readonly
  Players: readonly
  Entities: readonly
  Abilities: readonly
  Items: readonly
  Game: readonly
  GameUI: readonly
  Particles: readonly
  EventData: readonly
  LocalInventory: readonly
  SteamUGCQuery: readonly
  SteamUGCMatchingUGCType: readonly
  SteamUniverse: readonly
  DOTA_GameState: readonly
  DOTA_GC_TEAM: readonly
  DOTAConnectionState_t: readonly
  dotaunitorder_t: readonly
  DOTA_OVERHEAD_ALERT: readonly
  DOTA_HeroPickState: readonly
  DOTATeam_t: readonly
  DOTA_RUNES: readonly
  DOTA_UNIT_TARGET_TEAM: readonly
  DOTA_UNIT_TARGET_TYPE: readonly
  DOTA_UNIT_TARGET_FLAGS: readonly
  DOTALimits_t: readonly
  DOTAInventoryFlags_t: readonly
  EDOTA_ModifyGold_Reason: readonly
  DOTAUnitAttackCapability_t: readonly
  DOTAUnitMoveCapability_t: readonly
  EShareAbility: readonly
  DOTAMusicStatus_t: readonly
  DOTA_ABILITY_BEHAVIOR: readonly
  DAMAGE_TYPES: readonly
  ABILITY_TYPES: readonly
  SPELL_IMMUNITY_TYPES: readonly
  DOTADamageFlag_t: readonly
  EDOTA_ModifyXP_Reason: readonly
  GameActivity_t: readonly
  DOTAMinimapEvent_t: readonly
  DOTASlotType_t: readonly
  modifierfunction: readonly
  modifierstate: readonly
  DOTAModifierAttribute_t: readonly
  Attributes: readonly
  ParticleAttachment_t: readonly
  DOTA_MOTION_CONTROLLER_PRIORITY: readonly
  DOTASpeechType_t: readonly
  DOTAAbilitySpeakTrigger_t: readonly
  DotaCustomUIType_t: readonly
  DotaDefaultUIElement_t: readonly
  PlayerUltimateStateOrTime_t: readonly
  PlayerOrderIssuer_t: readonly
  OrderQueueBehavior_t: readonly
  CLICK_BEHAVIORS: readonly
  AbilityLearnResult_t: readonly
  DOTAKeybindCommand_t: readonly
  DOTA_SHOP_TYPE: readonly
