exclude_files = {
  "game/scripts/vscripts/pl/**",
  "game/scripts/vscripts/vendor/**"
}

new_globals = {
  "Precache",
  "Activate",
  "GameMode"
}

-- https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API
new_read_globals = {
  -- globals
  "AddFOWViewer",
  "AngleDiff",
  "AppendToLogFile",
  "ApplyDamage",
  "AxisAngleToQuaternion",
  "CalcClosestPointOnEntityOBB",
  "CalcDistanceBetweenEntityOBB",
  "CalcDistanceToLineSegment2D",
  "CancelEntityIOEvents",
  "ClearTeamCustomHealthbarColor",
  "CreateEffect",
  "CreateHeroForPlayer",
  "CreateHTTPRequestScriptVM",
  "CreateItem",
  "CreateItemOnPositionForLaunch",
  "CreateItemOnPositionSync",
  "CreateModifierThinker",
  "CreateTempTree",
  "CreateTrigger",
  "CreateTriggerRadiusApproximate",
  "CreateUnitByName",
  "CreateUnitByNameAsync",
  "CreateUnitFromTable",
  "cvar_getf",
  "cvar_setf",
  "DebugBreak",
  "DebugDrawBox",
  "DebugDrawBoxDirection",
  "DebugDrawCircle",
  "DebugDrawClear",
  "DebugDrawLine_vCol",
  "DebugDrawLine",
  "DebugDrawScreenTextLine",
  "DebugDrawSphere",
  "DebugDrawText",
  "DebugScreenTextPretty",
  "DoCleaveAttack",
  "DoEntFire",
  "DoEntFireByInstanceHandle",
  "DoIncludeScript",
  "DoScriptAssert",
  "DoUniqueString",
  "Dynamic_Wrap",
  "EmitAnnouncerSound",
  "EmitAnnouncerSoundForPlayer",
  "EmitAnnouncerSoundForTeam",
  "EmitAnnouncerSoundForTeamOnLocation",
  "EmitGlobalSound",
  "EmitSoundOn",
  "EmitSoundOnClient",
  "EmitSoundOnLocationForAllies",
  "EmitSoundOnLocationWithCaster",
  "EntIndexToHScript",
  "ExecuteOrderFromTable",
  "ExponentialDecay",
  "FileToString",
  "FindClearSpaceForUnit",
  "FindUnitsInLine",
  "FindUnitsInRadius",
  "FireEntityIOInputNameOnly",
  "FireEntityIOInputString",
  "FireEntityIOInputVec",
  "FireGameEvent",
  "FireGameEventLocal",
  "FrameTime",
  "GetEntityIndexForTreeId",
  "GetFrameCount",
  "GetFrostyBoostAmount",
  "GetFrostyPointsForRound",
  "GetGoldFrostyBoostAmount",
  "GetGoldFrostyPointsForRound",
  "GetGroundHeight",
  "GetGroundPosition",
  "GetItemCost",
  "GetListenServerHost",
  "GetMapName",
  "GetMaxOutputDelay",
  "GetPhysAngularVelocity",
  "GetPhysVelocity",
  "GetSystemDate",
  "GetSystemTime",
  "GetTeamHeroKills",
  "GetTeamName",
  "GetTreeIdForEntityIndex",
  "GetWorldMaxX",
  "GetWorldMaxY",
  "GetWorldMinX",
  "GetWorldMinY",
  "InitLogFile",
  "IsClient",
  "IsDedicatedServer",
  "IsInToolsMode",
  "IsMarkedForDeletion",
  "IsServer",
  "IsValidEntity",
  "LimitPathingSearchDepth",
  "LinkLuaModifier",
  "ListenToGameEvent",
  "LoadKeyValues",
  "LoadKeyValuesFromString",
  "MakeStringToken",
  "MinimapEvent",
  "Msg",
  "PauseGame",
  "PlayerInstanceFromIndex",
  "PrecacheEntityFromTable",
  "PrecacheEntityListFromTable",
  "PrecacheItemByNameAsync",
  "PrecacheItemByNameSync",
  "PrecacheModel",
  "PrecacheResource",
  "PrecacheUnitByNameAsync",
  "PrecacheUnitByNameSync",
  "PrintLinkedConsoleMessage",
  "RandomFloat",
  "RandomInt",
  "RandomVector",
  "RegisterSpawnGroupFilterProxy",
  "ReloadMOTD",
  "RemoveSpawnGroupFilterProxy",
  "ResolveNPCPositions",
  "RollPercentage",
  "RotateOrientation",
  "RotatePosition",
  "RotateQuaternionByAxisAngle",
  "RotationDelta",
  "RotationDeltaAsAngularVelocity",
  "rr_AddDecisionRule",
  "rr_CommitAIResponse",
  "rr_GetResponseTargets",
  "rr_QueryBestResponse",
  "Say",
  "ScreenShake",
  "SendFrostivusTimeElapsedToGC",
  "SendFrostyPointsMessageToGC",
  "SendOverheadEventMessage",
  "SendToConsole",
  "SendToServerConsole",
  "SetOpvarFloatAll",
  "SetOpvarFloatPlayer",
  "SetPhysAngularVelocity",
  "SetQuestName",
  "SetQuestPhase",
  "SetRenderingEnabled",
  "SetTeamCustomHealthbarColor",
  "ShowCustomHeaderMessage",
  "ShowGenericPopup",
  "ShowGenericPopupToPlayer",
  "ShowMessage",
  "SpawnEntityFromTableSynchronous",
  "SpawnEntityGroupFromTable",
  "SpawnEntityListFromTableAsynchronous",
  "SpawnEntityListFromTableSynchronous",
  "SplineQuaternions",
  "SplineVectors",
  "StartSoundEvent",
  "StartSoundEventFromPosition",
  "StartSoundEventFromPositionReliable",
  "StartSoundEventFromPositionUnreliable",
  "StartSoundEventReliable",
  "StartSoundEventUnreliable",
  "StopEffect",
  "StopListeningToAllGameEvents",
  "StopListeningToGameEvent",
  "StopSoundEvent",
  "StopSoundOn",
  "StringToFile",
  "Time",
  "TraceCollideable",
  "TraceHull",
  "TraceLine",
  "UnitFilter",
  "UnloadSpawnGroup",
  "UnloadSpawnGroupByHandle",
  "UpdateEventPoints",
  "UTIL_MessageText",
  "UTIL_MessageText_WithContext",
  "UTIL_MessageTextAll",
  "UTIL_MessageTextAll_WithContext",
  "UTIL_Remove",
  "UTIL_RemoveImmediate",
  "UTIL_ResetMessageText",
  "UTIL_ResetMessageTextAll",
  "VectorToAngles",
  "Warning",
  -- classes
  "Convars",
  "CustomGameEventManager",
  "CustomNetTables",
  "CustomUI",
  "Entities",
  "GameRules",
  "HeroList",
  "ParticleManager",
  "PlayerResource",
  "Tutorial",
  "Vector",
  -- constants
  --   convars flags
  "FCVAR_CHEAT",
  --   effects
  "EF_NODRAW",
  --   DOTA_GameState
  "DOTA_GAMERULES_STATE_INIT",
  "DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD",
  "DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP",
  "DOTA_GAMERULES_STATE_HERO_SELECTION",
  "DOTA_GAMERULES_STATE_STRATEGY_TIME",
  "DOTA_GAMERULES_STATE_TEAM_SHOWCASE",
  "DOTA_GAMERULES_STATE_PRE_GAME",
  "DOTA_GAMERULES_STATE_GAME_IN_PROGRESS",
  "DOTA_GAMERULES_STATE_POST_GAME",
  "DOTA_GAMERULES_STATE_DISCONNECT",
  --  DOTALimits_t
  "DOTA_DEFAULT_MAX_TEAM", -- (5) Default number of players per team.
  "DOTA_DEFAULT_MAX_TEAM_PLAYERS", -- (10) Default number of non-spectator players supported.
  "DOTA_MAX_PLAYER_TEAMS", -- (10) Max number of player teams supported.
  "DOTA_MAX_TEAM", -- (24) Max number of players per team.
  "DOTA_MAX_TEAM_PLAYERS", -- (24) Max number of non-spectator players supported.
  "DOTA_MAX_SPECTATOR_TEAM_SIZE", -- (40) How many spectators can watch.
  "DOTA_MAX_PLAYERS", -- (64) Max number of players connected to the server including spectators.
  --  DOTA_RUNES
  "DOTA_RUNE_INVALID",
  "DOTA_RUNE_DOUBLEDAMAGE",
  "DOTA_RUNE_HASTE",
  "DOTA_RUNE_ILLUSION",
  "DOTA_RUNE_INVISIBILITY",
  "DOTA_RUNE_REGENERATION",
  "DOTA_RUNE_ARCANE",
  "DOTA_RUNE_BOUNTY",
  "DOTA_RUNE_COUNT",
  "DOTA_RUNE_HAUNTED",
  "DOTA_RUNE_SPOOKY",
  "DOTA_RUNE_RAPIER",
  "DOTA_RUNE_TURBO",
  "DOTA_RUNE_MYSTERY",
  "DOTA_HALLOWEEN_RUNE_COUNT",
  -- DOTATeam_t
  "DOTA_TEAM_FIRST",
  "DOTA_TEAM_GOODGUYS",
  "DOTA_TEAM_BADGUYS",
  "DOTA_TEAM_NEUTRALS",
  "DOTA_TEAM_NOTEAM",
  "DOTA_TEAM_CUSTOM_1",
  "DOTA_TEAM_CUSTOM_MIN",
  "DOTA_TEAM_CUSTOM_2",
  "DOTA_TEAM_CUSTOM_3",
  "DOTA_TEAM_CUSTOM_COUNT",
  "DOTA_TEAM_CUSTOM_4",
  "DOTA_TEAM_CUSTOM_5",
  "DOTA_TEAM_CUSTOM_6",
  "DOTA_TEAM_CUSTOM_7",
  "DOTA_TEAM_CUSTOM_8",
  "DOTA_TEAM_CUSTOM_MAX",
  "DOTA_TEAM_COUNT",
  -- DOTAScriptInventorySlot_t
  "DOTA_ITEM_SLOT_1", -- (0)
  "DOTA_ITEM_SLOT_2", -- (1)
  "DOTA_ITEM_SLOT_3", -- (2)
  "DOTA_ITEM_SLOT_4", -- (3)
  "DOTA_ITEM_SLOT_5", -- (4)
  "DOTA_ITEM_SLOT_6", -- (5)
  "DOTA_STASH_SLOT_1", -- (6)
  "DOTA_STASH_SLOT_2", -- (7)
  "DOTA_STASH_SLOT_3", -- (8)
  "DOTA_STASH_SLOT_4", -- (9)
  "DOTA_STASH_SLOT_5", -- (10)
  "DOTA_STASH_SLOT_6", -- (11)
}
