arrowParens: always
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: auto
htmlWhitespaceSensitivity: ignore
quoteProps: consistent
semi: true
singleAttributePerLine: false
singleQuote: false
trailingComma: all
xmlSelfClosingSpace: true
xmlWhitespaceSensitivity: ignore
