std = "selene-busted+selene-dota2+selene-dota2-custom_game"
exclude = [
  ".luarocks/**",
  "lua_modules/**",
  "game/scripts/vscripts/fsm.lua",
  "game/scripts/vscripts/moses.lua",
  "game/scripts/vscripts/pl/**",
  "tmp/**",
]
