version: "3"

vars:
  PANORAMA_LAYOUTS_SRC_PATH: content/panorama/layout
  PANORAMA_SCRIPTS_SRC_PATH: src/content/panorama/scripts
  PANORAMA_STYLES_SRC_PATH: content/panorama/styles
  TASKS_SRC_PATH: scripts
  VSCRIPTS_SRC_PATH: game/scripts/vscripts

tasks:
  default:
    cmds:
      - task: format
      - task: lint
      - task: test
      - task: build

  format:
    desc: Run all formatters
    cmds:
      - task: tasks:format
      - task: vscripts:format
      - task: panorama:format

  lint:
    desc: Run all linters
    cmds:
      - task: tasks:lint
      - task: vscripts:lint
      - task: panorama:lint

  test:
    desc: Run all tests
    cmds:
      - task: vscripts:test

  clean:
    desc: Remove all compiled, generated and linked files
    cmd: bun scripts/index.ts clean

  link:
    desc: Link source files to game directories
    cmd: bun scripts/index.ts link

  build:
    desc: Build everything
    deps: [link]
    cmd: bun scripts/index.ts build

  launch:game:
    desc: Launch Dota2
    cmd: bun scripts/index.ts launch game

  launch:tools:
    desc: Launch SDK
    cmd: bun scripts/index.ts launch tools

  vscripts:format:
    desc: Format vscripts
    cmd: stylua --verify "{{.VSCRIPTS_SRC_PATH}}"

  vscripts:lint:
    desc: Lint vscripts
    cmd: selene "{{.VSCRIPTS_SRC_PATH}}"

  vscripts:test:
    desc: Test vscripts
    cmd: luarocks test

  panorama:format:
    desc: Format all panorama files
    cmds:
      - task: panorama:layouts:format
      - task: panorama:scripts:format
      - task: panorama:styles:format

  panorama:lint:
    desc: Lint all panorama files
    cmds:
      - task: panorama:layouts:lint
      - task: panorama:scripts:lint
      - task: panorama:styles:lint

  panorama:layouts:format:
    desc: Format panorama layouts
    cmd: bun x prettier --write '{{.PANORAMA_LAYOUTS_SRC_PATH}}/**/*.xml'

  panorama:layouts:lint:
    desc: Lint panorama layouts
    cmd: echo "not implemented"

  panorama:scripts:format:
    desc: Format panorama scripts
    cmd: bun x @biomejs/biome format --write "{{.PANORAMA_SCRIPTS_SRC_PATH}}"

  panorama:scripts:lint:
    desc: Lint panorama scripts
    cmd: bun x @biomejs/biome check "{{.PANORAMA_SCRIPTS_SRC_PATH}}"

  panorama:scripts:build:
    desc: Build panorama scripts
    cmd: bun x tsc --build "{{.PANORAMA_SCRIPTS_SRC_PATH}}" --verbose

  panorama:styles:format:
    desc: Format panorama styles
    cmds:
      - bun x stylelint --fix "{{.PANORAMA_STYLES_SRC_PATH}}"
      - bun x prettier --write '{{.PANORAMA_STYLES_SRC_PATH}}/**/*.css'

  panorama:styles:lint:
    desc: Lint panorama styles
    cmd: bun x stylelint "{{.PANORAMA_STYLES_SRC_PATH}}"

  tasks:format:
    desc: Format tasks
    cmd: bun x @biomejs/biome format --write "{{.TASKS_SRC_PATH}}"

  tasks:lint:
    desc: Lint tasks
    cmd: bun x @biomejs/biome check "{{.TASKS_SRC_PATH}}"
