version: 3

dotenv: [".env"]

vars:
  LX_LUA_VERSION: "jit"
  LX_ARGS: "--lua-version {{ .LX_LUA_VERSION }}"
  SRC_PANO_LAYOUTS: '{{ joinPath .ROOT_DIR "content" "panorama" "layout" }}'
  SRC_PANO_SCRIPTS: '{{ joinPath .ROOT_DIR "src" "content" "panorama" "scripts" }}'
  SRC_PANO_STYLES: '{{ joinPath .ROOT_DIR "src" "content" "panorama" "styles" }}'
  SRC_VSCRIPTS: '{{ joinPath .ROOT_DIR "game" "scripts" "vscripts" }}'
  SRC_VSCRIPTS_TESTS: '{{ joinPath .ROOT_DIR "spec" }}'
  SRC_TASKS: '{{ joinPath .ROOT_DIR "src" "tasks" }}'
  EMMYLUA_CONFIG: '{{ joinPath .ROOT_DIR ".emmyrc.json" }}'
  STYLUA_CONFIG: '{{ joinPath .ROOT_DIR ".stylua.toml" }}'
  SELENE_CONFIG: '{{ joinPath .ROOT_DIR "selene.toml" }}'
  SELENE_TESTS_CONFIG: '{{ joinPath .SRC_VSCRIPTS_TESTS "selene.toml" }}'
  TASKS_ENTRYPOINT: '{{ joinPath .SRC_TASKS "main.ts" }}'
  TASKS_RUN: 'bun run -- "{{ .TASKS_ENTRYPOINT }}"'

tasks:
  default:
    cmds:
      - task: format
      - task: lint
      - task: test
      - task: build

  format:
    desc: Run all formatters
    cmds:
      - task: format:tasks
      - task: format:vscripts
      - task: format:panorama

  lint:
    desc: Run all linters
    cmds:
      - task: lint:tasks
      - task: lint:vscripts
      - task: lint:panorama

  test:
    desc: Run all tests
    cmds:
      - task: test:vscripts

  clean:
    desc: Remove all compiled, generated and linked files
    cmd: "{{ .TASKS_RUN }} clean {{ .CLI_ARGS }}"

  link:
    desc: Link source files to game directories
    cmd: "{{ .TASKS_RUN }} link {{ .CLI_ARGS }}"

  launch:game:
    desc: Launch Dota2
    cmd: "{{ .TASKS_RUN }} launch {{ .CLI_ARGS }} game"

  launch:sdk:
    desc: Launch SDK (Workshop Tools)
    cmd: "{{ .TASKS_RUN }} launch {{ .CLI_ARGS }} sdk"

  _build:
    internal: true
    cmd: "{{ .TASKS_RUN }} build {{ .CLI_ARGS }} {{ .ARGS }}"

  build:
    desc: Build everything
    cmd: { task: "_build" }

  build:pano:scripts:
    desc: Build panorama scripts
    cmds:
      - task: "_build"
        vars: { ARGS: "scripts" }

  build:pano:styles:
    desc: Build panorama styles
    cmds:
      - task: "_build"
        vars: { ARGS: "styles" }

  _compile:
    internal: true
    cmd: "{{ .TASKS_RUN }} compile {{ .CLI_ARGS }} {{ .ARGS }}"

  compile:
    desc: Compile everything
    deps: [build]
    cmds:
      - task: "_compile"

  compile:maps:
    desc: Compile maps
    cmds:
      - task: "_compile"
        vars: { ARGS: "maps" }

  compile:panorama:
    desc: Compile all panorama resources
    cmds:
      - task: "_compile"
        vars: { ARGS: "panorama" }

  compile:pano:scripts:
    desc: Compile panorama scripts
    cmds:
      - task: "build:pano:scripts"
      - task: "_compile"
        vars: { ARGS: "scripts" }

  compile:pano:styles:
    desc: Compile panorama styles
    cmds:
      - task: "build:pano:styles"
      - task: "_compile"
        vars: { ARGS: "styles" }

  compile:resources:
    desc: Compile resources
    cmds:
      - task: "_compile"
        vars: { ARGS: "resources" }

  format:vscripts:
    desc: Format vscripts
    cmd: stylua --verify --config-path "{{ .STYLUA_CONFIG }}" "{{ .SRC_VSCRIPTS }}"

  lint:vscripts:
    desc: Lint vscripts
    cmds:
      - emmylua_check --config "{{ .EMMYLUA_CONFIG }}" "{{ .ROOT_DIR }}"
      - selene --config "{{ .SELENE_CONFIG }}" "{{ .SRC_VSCRIPTS }}"
      - selene --config "{{ .SELENE_TESTS_CONFIG }}" "{{ .SRC_VSCRIPTS_TESTS }}"

  test:vscripts:
    desc: Test vscripts
    cmd: lx {{ .LX_ARGS }} test -- {{ .CLI_ARGS }}

  format:panorama:
    desc: Format all panorama files
    cmds:
      - task: format:pano:layouts
      - task: format:pano:scripts
      - task: format:pano:styles

  lint:panorama:
    desc: Lint all panorama files
    cmds:
      - task: lint:pano:layouts
      - task: lint:pano:scripts
      - task: lint:pano:styles

  format:pano:layouts:
    desc: Format panorama layouts
    cmd: dprint fmt '{{ joinPath .SRC_PANO_LAYOUTS "**" }}'

  lint:pano:layouts:
    desc: Lint panorama layouts
    cmd: echo "not implemented"

  format:pano:scripts:
    desc: Format panorama scripts
    cmd: dprint fmt '{{ joinPath .SRC_PANO_SCRIPTS "**" }}'

  lint:pano:scripts:
    desc: Lint panorama scripts
    dir: "{{ .SRC_PANO_SCRIPTS }}"
    cmd: bun x -- "@biomejs/biome" lint {{ .CLI_ARGS }}

  format:pano:styles:
    desc: Format panorama styles
    cmd: dprint fmt '{{ joinPath .SRC_PANO_STYLES "**" }}'

  lint:pano:styles:
    desc: Lint panorama styles
    dir: "{{ .SRC_PANO_STYLES }}"
    cmd: echo "not implemented"
    # cmd: bun x -- "@biomejs/biome" lint {{ .CLI_ARGS }}

  format:tasks:
    desc: Format tasks
    cmd: dprint fmt '{{ joinPath .SRC_TASKS "**" }}'

  lint:tasks:
    desc: Lint tasks
    dir: "{{ .SRC_TASKS }}"
    cmd: bun x -- "@biomejs/biome" lint {{ .CLI_ARGS }}
