version: 3

dotenv: [".env"]

vars:
  PANORAMA_LAYOUTS_SRC_PATH: "content/panorama/layout"
  PANORAMA_SCRIPTS_SRC_PATH: "src/content/panorama/scripts"
  PANORAMA_STYLES_SRC_PATH: "content/panorama/styles"
  VSCRIPTS_SRC_PATH: "game/scripts/vscripts"
  TASKS_SRC_PATH: "src/tasks"
  TASKS_ENTRYPOINT: "{{ .TASKS_SRC_PATH }}/main.ts"
  TASKS_DEBUG_FLAGS: '{{ empty .DEBUG | ternary "" "--debug" }}'
  LX_ARGS: "--lua-version jit"

tasks:
  default:
    cmds:
      - task: format
      - task: lint
      - task: test
      - task: build

  format:
    desc: Run all formatters
    cmds:
      - task: format:tasks
      - task: format:vscripts
      - task: format:panorama

  lint:
    desc: Run all linters
    cmds:
      - task: lint:tasks
      - task: lint:vscripts
      - task: lint:panorama

  test:
    desc: Run all tests
    cmds:
      - task: test:vscripts

  clean:
    desc: Remove all compiled, generated and linked files
    cmd: bun run -- "{{ .TASKS_ENTRYPOINT }}" {{ .TASKS_DEBUG_FLAGS }} clean

  link:
    desc: Link source files to game directories
    cmd: bun run -- "{{ .TASKS_ENTRYPOINT }}" {{ .TASKS_DEBUG_FLAGS }} link

  launch:game:
    desc: Launch Dota2
    cmd: bun run -- "{{ .TASKS_ENTRYPOINT }}" {{ .TASKS_DEBUG_FLAGS }} launch game

  launch:sdk:
    desc: Launch SDK (Workshop Tools)
    cmd: bun run -- "{{ .TASKS_ENTRYPOINT }}" {{ .TASKS_DEBUG_FLAGS }} launch sdk

  build:
    desc: Build everything
    deps: [link]
    cmd: bun run -- "{{ .TASKS_ENTRYPOINT }}" {{ .TASKS_DEBUG_FLAGS }} build

  build:maps:
    desc: Build maps
    cmd: bun run -- "{{ .TASKS_ENTRYPOINT }}" {{ .TASKS_DEBUG_FLAGS }} build maps

  build:panorama:scripts:
    desc: Build panorama scripts
    cmd: bun run -- "{{ .TASKS_ENTRYPOINT }}" {{ .TASKS_DEBUG_FLAGS }} build panorama-scripts

  build:resources:
    deps: [build:panorama:scripts]
    desc: Build resources
    cmd: bun run -- "{{ .TASKS_ENTRYPOINT }}" {{ .TASKS_DEBUG_FLAGS }} build resources

  format:vscripts:
    desc: Format vscripts
    cmd: stylua --verify "{{ .VSCRIPTS_SRC_PATH }}"

  lint:vscripts:
    desc: Lint vscripts
    cmd: selene "{{ .VSCRIPTS_SRC_PATH }}"

  test:vscripts:
    desc: Test vscripts
    cmd: lx {{ .LX_ARGS }} test -- {{ .CLI_ARGS }}

  format:panorama:
    desc: Format all panorama files
    cmds:
      - task: format:panorama:layouts
      - task: format:panorama:scripts
      - task: format:panorama:styles

  lint:panorama:
    desc: Lint all panorama files
    cmds:
      - task: lint:panorama:layouts
      - task: lint:panorama:scripts
      - task: lint:panorama:styles

  format:panorama:layouts:
    desc: Format panorama layouts
    dir: "{{ .PANORAMA_LAYOUTS_SRC_PATH }}"
    cmd: bun x -- prettier --write {{ .CLI_ARGS }} "**/*.xml"

  lint:panorama:layouts:
    desc: Lint panorama layouts
    cmd: echo "not implemented"

  format:panorama:scripts:
    desc: Format panorama scripts
    dir: "{{ .PANORAMA_SCRIPTS_SRC_PATH }}"
    cmd: bun x -- "@biomejs/biome" format --write {{ .CLI_ARGS }}

  lint:panorama:scripts:
    desc: Lint panorama scripts
    dir: "{{ .PANORAMA_SCRIPTS_SRC_PATH }}"
    cmd: bun x -- "@biomejs/biome" check {{ .CLI_ARGS }}

  format:panorama:styles:
    desc: Format panorama styles
    dir: "{{ .PANORAMA_STYLES_SRC_PATH }}"
    cmds:
      - bun x -- stylelint --fix {{ .CLI_ARGS }} .
      - bun x -- prettier --write {{ .CLI_ARGS }} "**/*.css"

  lint:panorama:styles:
    desc: Lint panorama styles
    dir: "{{ .PANORAMA_STYLES_SRC_PATH }}"
    cmd: bun x -- stylelint {{ .CLI_ARGS }} .

  format:tasks:
    desc: Format tasks
    dir: "{{ .TASKS_SRC_PATH }}"
    cmd: bun x -- "@biomejs/biome" format --write {{ .CLI_ARGS }}

  lint:tasks:
    desc: Lint tasks
    dir: "{{ .TASKS_SRC_PATH }}"
    cmd: bun x -- "@biomejs/biome" check {{ .CLI_ARGS }}
