--- Missing or renamed enums.
-- @module invokation.const.enums

local M = {}

--- Missing (GameActivity_t) ACT_INVALID
M.ACT_INVALID = -1

--- Renamed (ABILITY_TYPES) ABILITY_TYPE_ATTRIBUTES
M.DOTA_ABILITY_TYPE_ATTRIBUTES = ABILITY_TYPE_ATTRIBUTES
--- Renamed (ABILITY_TYPES) ABILITY_TYPE_BASIC
M.DOTA_ABILITY_TYPE_BASIC = ABILITY_TYPE_BASIC
--- Renamed (ABILITY_TYPES) ABILITY_TYPE_HIDDEN
M.DOTA_ABILITY_TYPE_HIDDEN = ABILITY_TYPE_HIDDEN
--- Renamed (ABILITY_TYPES) ABILITY_TYPE_ULTIMATE
M.DOTA_ABILITY_TYPE_ULTIMATE = ABILITY_TYPE_ULTIMATE

--- Missing (DOTA_ABILITY_BEHAVIOR) DOTA_ABILITY_BEHAVIOR_NOASSIST
M.DOTA_ABILITY_BEHAVIOR_NOASSIST = 0

return M
