export const INVOKER = {
  ABILITY_QUAS: "invoker_quas",
  ABILITY_WEX: "invoker_wex",
  ABILITY_EXORT: "invoker_exort",
  ABILITY_INVOKE: "invoker_invoke",
  ABILITY_COLD_SNAP: "invoker_cold_snap",
  ABILITY_GHOST_WALK: "invoker_ghost_walk",
  ABILITY_ICE_WALL: "invoker_ice_wall",
  ABILITY_EMP: "invoker_emp",
  ABILITY_TORNADO: "invoker_tornado",
  ABILITY_ALACRITY: "invoker_alacrity",
  ABILITY_SUN_STRIKE: "invoker_sun_strike",
  ABILITY_FORGE_SPIRIT: "invoker_forge_spirit",
  ABILITY_CHAOS_METEOR: "invoker_chaos_meteor",
  ABILITY_DEAFENING_BLAST: "invoker_deafening_blast",
  // FIXME: Talent ability names shouldn't be hardcoded.
  // vscript dynamically parses the hero KeyValues for these names.
  ABILITY_TALENT_L10_RIGHT: "special_bonus_unique_invoker_10",
  ABILITY_TALENT_L10_LEFT: "special_bonus_unique_invoker_6",
  ABILITY_TALENT_L15_RIGHT: "special_bonus_unique_invoker_13",
  ABILITY_TALENT_L15_LEFT: "special_bonus_unique_invoker_9",
  ABILITY_TALENT_L20_RIGHT: "special_bonus_unique_invoker_3",
  ABILITY_TALENT_L20_LEFT: "special_bonus_unique_invoker_5",
  ABILITY_TALENT_L25_RIGHT: "special_bonus_unique_invoker_2",
  ABILITY_TALENT_L25_LEFT: "special_bonus_unique_invoker_11",

  ORB_ABILITIES: {} as { [key: string]: string },
  SPELL_ABILITIES: {} as { [key: string]: string },
  TALENT_ABILITIES: [] as string[],
};

INVOKER.ORB_ABILITIES = {
  [INVOKER.ABILITY_QUAS]: INVOKER.ABILITY_QUAS,
  [INVOKER.ABILITY_WEX]: INVOKER.ABILITY_WEX,
  [INVOKER.ABILITY_EXORT]: INVOKER.ABILITY_EXORT,
};

INVOKER.SPELL_ABILITIES = {
  [INVOKER.ABILITY_COLD_SNAP]: INVOKER.ABILITY_COLD_SNAP,
  [INVOKER.ABILITY_GHOST_WALK]: INVOKER.ABILITY_GHOST_WALK,
  [INVOKER.ABILITY_ICE_WALL]: INVOKER.ABILITY_ICE_WALL,
  [INVOKER.ABILITY_EMP]: INVOKER.ABILITY_EMP,
  [INVOKER.ABILITY_TORNADO]: INVOKER.ABILITY_TORNADO,
  [INVOKER.ABILITY_ALACRITY]: INVOKER.ABILITY_ALACRITY,
  [INVOKER.ABILITY_SUN_STRIKE]: INVOKER.ABILITY_SUN_STRIKE,
  [INVOKER.ABILITY_FORGE_SPIRIT]: INVOKER.ABILITY_FORGE_SPIRIT,
  [INVOKER.ABILITY_CHAOS_METEOR]: INVOKER.ABILITY_CHAOS_METEOR,
  [INVOKER.ABILITY_DEAFENING_BLAST]: INVOKER.ABILITY_DEAFENING_BLAST,
};

INVOKER.TALENT_ABILITIES = [
  INVOKER.ABILITY_TALENT_L10_RIGHT,
  INVOKER.ABILITY_TALENT_L10_LEFT,
  INVOKER.ABILITY_TALENT_L15_RIGHT,
  INVOKER.ABILITY_TALENT_L15_LEFT,
  INVOKER.ABILITY_TALENT_L20_RIGHT,
  INVOKER.ABILITY_TALENT_L20_LEFT,
  INVOKER.ABILITY_TALENT_L25_RIGHT,
  INVOKER.ABILITY_TALENT_L25_LEFT,
];
